- data_path: data/tokenized/fineweb-2-ko
  name: fineweb_ko
  original_prob: null
  weight: 0.94
- data_path: data/tokenized/fineweb-2-ko
  name: fineweb_ko
  original_prob: null
  weight: 0.06
